import { StyleSheet } from 'react-native';

export const headerStyles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
    padding: 10,
  },
  mainLogo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoText: {
    color: '#FF4500',
    fontSize: 24,
    fontWeight: 'bold',
    textShadowColor: '#4f0000',
    textShadowOffset: { width: 3, height: 6 },
    textShadowRadius: 2,
  },
  logoTextNotes: {
    color: '#00FF00',
    fontSize: 24,
    fontWeight: 'bold',
    marginLeft: 5,
    textShadowColor: '#004c1b',
    textShadowOffset: { width: 2, height: 4 },
    textShadowRadius: 2,
  },
  menuIcon: {
    fontSize: 30,
  },
  dropdown: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 300,
    height: 400,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    padding: 20,
    borderWidth: 2,
    borderColor: 'rgb(114, 255, 255)',
    borderRadius: 5,
    zIndex: 999,
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    fontSize: 30,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'black',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    marginBottom: 15,
    padding: 5,
  },
  searchInput: {
    flex: 1,
    height: 40,
    color: 'white',
  },
  searchButton: {
    minWidth: 60,
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: 'black',
    borderWidth: 2,
    borderColor: 'red',
    borderRadius: 5,
    marginLeft: 10,
  },
  searchButtonText: {
    color: 'white',
    fontSize: 14,
  },
  searchIcon: {
    fontSize: 20,
    marginRight: 5,
  },
  logoutText: {
    color: 'white',
    fontSize: 16,
    marginBottom: 15,
  },
  followMe: {
    marginBottom: 15,
  },
  socialIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  socialIcon: {
    fontSize: 24,
    color: 'white',
  },
});
